### ISSUE TITLE
$validate->errors()->first() 无法获得正确的错误消息

### ISSUE THREAD

**Issue by z-perfe** [webman-tech/laravel-validation#10]
$validate->errors()->first()
返回的是:  validation.integer
具体哪个字段不知道

**Comment by krissss** [comment]
$validate->errors()->all()  可以返回所有错误信息，具体看下 laravel 的文档
返回的是 validation.integer 是因为没有加国际化翻译，具体参考：https://github.com/webman-tech/laravel-validation#locale-%E6%9C%AC%E5%9C%B0%E5%8C%96%E7%BF%BB%E8%AF%91%E9%9C%80%E6%B1%82
