### ISSUE TITLE
laravel-translation 这个依赖没有意义吧

### ISSUE THREAD

**Issue by yuanzhihai** [webman-tech/laravel-validation#2]
laravel-translation 这个依赖没有意义吧

**Comment by krissss** [comment]
按道理是可选依赖（可以自行提供 Translator 实现），下个版本去除
但为了验证消息的翻译，Translator  是必须的

**Comment by krissss** [comment]
已处理

[locale 本地化翻译需求](https://github.com/webman-tech/laravel-validation#locale-%E6%9C%AC%E5%9C%B0%E5%8C%96%E7%BF%BB%E8%AF%91%E9%9C%80%E6%B1%82)
