### ISSUE TITLE
php 7.2 无法使用

### ISSUE THREAD

**Issue by jiejia** [webman-tech/laravel-validation#3]
Problem 1
    - illuminate/validation[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (7.2.34) does not satisfy that requirement.
    - illuminate/validation[v8.12.0, ..., v8.83.25] require php ^7.3|^8.0 -> your php version (7.2.34) does not satisfy that requirement.
    - illuminate/validation[v9.0.0, ..., v9.36.4] require php ^8.0.2 -> your php version (7.2.34) does not satisfy that requirement.
    - webman-tech/laravel-validation v1.0.0 requires illuminate/validation >=8 -> satisfiable by illuminate/validation[v8.0.0, ..., v8.83.25, v9.0.0, ..., v9.36.4].
    - Root composer.json requires webman-tech/laravel-validation 1.0.0 -> satisfiable by webman-tech/laravel-validation[v1.0.0].

**Comment by krissss** [comment]
更新下到 1.1.1

**Comment by jiejia** [comment]
可以了
