### ISSUE TITLE
本地windows开发没有错误 运行到正式环境宝塔php8.1 出现下面的错误！

### ISSUE THREAD

**Issue by bobtmee** [webman-tech/laravel-validation#4]
TypeError: WebmanTech\LaravelValidation\Facades\Validator::getTranslator(): Return value must be of type Illuminate\Contracts\Translation\Translator, null returned in /www/wwwroot/api/vendor/webman-tech/laravel-validation/src/Facades/Validator.php:58
希望作者能帮忙解决下  联系邮箱312331698@qq.com

**Comment by krissss** [comment]
看下 `config/plugin/laravel-validation/app.php` 下的 `translation` 是否返回的是 null

另外：
建议升级一下最新版本，使用该方式配置一下本地化 [locale-本地化翻译需求](https://github.com/webman-tech/laravel-validation#locale-%E6%9C%AC%E5%9C%B0%E5%8C%96%E7%BF%BB%E8%AF%91%E9%9C%80%E6%B1%82)
