### ISSUE TITLE
已经安装了illuminate/database,还是报错Presence verifier has not been set

### ISSUE THREAD

**Issue by jiejia** [webman-tech/laravel-validation#5]
RuntimeException: Presence verifier has not been set. in /www/wwwroot/webman-admin.veteran.test/webman/vendor/illuminate/validation/Validator.php:1413

![image](https://user-images.githubusercontent.com/3644151/211487323-612869ea-9779-4d1c-b17f-d700d5fa1bbd.png)

**Comment by krissss** [comment]
可能是 9.x 版本的原因，我需要验证一下

**Comment by krissss** [comment]
测试 9.x 一切正常

看你使用的版本是 v1.0.2的，麻烦更新一下使用最新版本（v1.1.0 之后才支持 unique 验证器的）

**Comment by jiejia** [comment]
composer阿里云镜像里没有1.1.1及以上版本，换成腾讯云镜像更新了可以了
