### ISSUE TITLE
valiator 未定义

### ISSUE THREAD

**Issue by yun3948** [webman-tech/laravel-validation#6]
你好，我想问下我按照文档安装了以后写了一个测试的提示了这个错误。 能不能问下可能是哪里的问题？

**Comment by krissss** [comment]
单词拼错了？validator

**Comment by krissss** [comment]
不好意思，是我文档问题，确实单词写错了

**Comment by yun3948** [comment]
好的

**Comment by yun3948** [comment]
文档里面  $validator->errors->first()   errors应该是一个方法

**Comment by krissss** [comment]
已处理，谢谢

**Comment by pengxuxu** [comment]
webman的[官方的插件文档](https://www.workerman.net/plugin/89)上的也出现了上述两个错误

**Comment by krissss** [comment]
谢谢，忘记更新了，已修改

**Comment by pengxuxu** [comment]
@krissss 谢谢你,提供了这么好用包！
