### ISSUE TITLE
valiator 函數是哪來的?

### ISSUE THREAD

**Issue by jiangjiangdev** [webman-tech/laravel-validation#8]
如題

**Comment by krissss** [comment]
你单词拼错了吧，validator

**Comment by jiangjiangdev** [comment]
抱歉拼錯了, 但這個函數一樣不存在, 您是自己在 helper 裡新增的吧?

**Comment by krissss** [comment]
composer autoload 自动加载的，不需要自己在项目下添加，请问你怎么安装的这个库，另外提示的错误麻烦发一下看看
