### ISSUE TITLE
大佬，能不加一个和laravel一样的request绑定验证的功能

### ISSUE THREAD

**Issue by lucasliang2022** [webman-tech/laravel-validation#9]
大佬，能不加一个和laravel一样的request绑定验证的功能

**Comment by krissss** [comment]
$request->validate() ?

**Comment by lucasliang2022** [comment]
`<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class BaseRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @param Validator $validator
     * @return void
     * @throws HttpResponseException
     */
    protected function failedValidation(Validator $validator) :void
    {
        $error = $validator->errors()->first();
        $response = apiErrorJson($error);
        throw new HttpResponseException($response);
    }
}
`

**Comment by lucasliang2022** [comment]
[laravel 10 wenda](https://learnku.com/docs/laravel/9.x/validation/12219#ecf8bc)

**Comment by krissss** [comment]
可能不好加过来，因为 FormRequest 严重依赖 laravel 的 request，不同于 webman 的 request
能想到的办法可能就是自己实现一个类似的 FormRequest 组件
